#!/bin/bash
#
# execute sudo after copying over MIT-magic-cookie
# (c) 2016 Jan Jaeger
#

which=$( which which )
xauth=$( ${which} xauth )
id=$( $which id )
sudo=$( $which sudo )

i=$(( $#-1 ))
while [[ ${i} -ge 0 ]] ; do
     token=${BASH_ARGV[$i]}
     #echo "i=$i: $token"
     if [[ "x${token}" == "x-u" ]] ; then
         (( i-=1 ))
         sudo_user=${BASH_ARGV[$i]}
     fi
     if [[ "x${token}" == "xsu" ]] ; then
         if [[ "x${BASH_ARGV[0]}" == "x-" ]] || [[ ${i} -eq 0 ]] ; then
             sudo_user="root"
         elif id ${BASH_ARGV[0]} >/dev/null 2>&1 ; then
             sudo_user=${BASH_ARGV[0]}
         fi
         break
     fi
     (( --i ))
done
echo $sudo_user

cookie=$( ${xauth} list ${DISPLAY} )
#echo $cookie

${sudo} -u ${sudo_user} -i ${xauth} add ${cookie} 2>/dev/null
exec ${sudo} $*

